name: isp_app
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: ^2.0.7
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.1
  provider: ^6.1.2
  path_provider: ^2.1.3
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/img/
